### ISSUE TITLE
SLO alerts throttling

### ISSUE THREAD

**Issue by NaitoKenzo** [DataDog/documentation#10261]
**Is your feature request related to a problem? Please describe.**
SLO alerts are very noisy when SLOs hover on the limit. Which does happen quite often because SLOs evolve slowly over time.

**Describe the solution you'd like**
I'd like to be able to define alert conditions to throttle alert count over a period of time.

**Describe alternatives you've considered**
- Stop using alerts in favour of a weekly review
- Muting alerts for some time

**Additional context**

**Comment by apigirl** [comment]
Hi @NaitoKenzo,

Thanks for this suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
