### ISSUE TITLE
Fixing a forecast window in the main page

### ISSUE THREAD

**Issue by spaem66** [DataDog/documentation#10443]
**Is your feature request related to a problem? Please describe.**

**Is your feature request related to a problem? Please describe.**
When using Time Series dashboards, an important feature for us is the forecast graph.
Unfortunately, it seems that the forecast can be accessed only by editing (one of the top right control bottons) the Time Window and selecting the kind of forecast function useful for you (e.g: linear, seasonal, etc).
There is no way to fix the forecast panel in the main time series window, without entering in “full screen mode”:
 
 
![image](https://user-images.githubusercontent.com/26812173/116521945-e432ce00-a8d4-11eb-9529-19c67a83c50c.png)

![image](https://user-images.githubusercontent.com/26812173/116521968-eac14580-a8d4-11eb-8ec8-c6206239cd42.png)

**Describe the solution you'd like**
We would like to add and fix the forecast window in the main page, avoiding the “full screen” control.

**Comment by apigirl** [comment]
Hi @spaem66 ,

Thanks for this suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
