### ISSUE TITLE
Python dependency opentelemetry-ext-datadog does not exist

### ISSUE THREAD

**Issue by sylvainmouquet** [DataDog/documentation#11238]
## Documentation Page
https://docs.datadoghq.com/fr/tracing/setup_overview/open_standards/python/

## Issue Description
`pip install opentelemetry-ext-datadog`
ERROR: Could not find a version that satisfies the requirement opentelemetry-ext-datadog
ERROR: No matching distribution found for opentelemetry-ext-datadog

According the link https://www.datadoghq.com/blog/instrument-python-apps-with-datadog-and-opentelemetry/
the dependency name is `pip install opentelemetry-exporter-datadog
`

**Comment by apigirl** [comment]
hi @sylvainmouquet - thank you so much for reporting this! It is a case that our French got outdated with our English, because you can see that the English example is correct - https://docs.datadoghq.com/tracing/setup_overview/open_standards/python/#installation. I just made sure to update the French in our translation tool, so you should see it updated in the docs site within a few days.
