### ISSUE TITLE
Metrics are double-documented

### ISSUE THREAD

**Issue by gtrummell** [DataDog/documentation#1126]
In [Datadog-AWS ELB Integration](http://docs.datadoghq.com/integrations/awselb/) under metrics, several metrics are double documented with conflicting rates, including `aws.elb.httpcode_elb_4xx` and `aws.elb.httpcode_elb_5xx`.

In addition, it is unclear what notes such as _gauged per minute_ and _rated per second_ mean.

**Comment by gtrummell** [comment]
After speaking with Charly Fontaine (thank you Charly!), I reviewed some links he sent us. Thanks to those links, I have a better understanding of how Datadog collects metrics. I'd still suggest linking to an explanation of units such as rate and gauge since we engineers are a lazy lot.

The following metrics are still double-listed:

- aws.elb.httpcode_elb_4xx
- aws.elb.httpcode_elb_5xx

**Comment by l0k0ms** [comment]
Hello, 
The layout issue is now fixed on our documentation and we wrote a KB in order to detail what are the different metric types used by your Datadog application: https://help.datadoghq.com/hc/en-us/articles/206955236-Metric-types-in-Datadog

Feel free to reach out to our support team directly if you have any further question on this topic.
