### ISSUE TITLE
Export logs JSON to monitor

### ISSUE THREAD

**Issue by aitolkyn99** [DataDog/documentation#11410]
<!-- Is this a documentation feature request? If not, and it is a feature request for the Datadog product, please contact our support team at https://docs.datadoghq.com/help/. They keep track of feature requests and can let you know if Datadog moves forward with implementing it. --!>

**I need to access logs' content (e.g.: message, attributes, etc.) from my monitor to use the values in the event message field. But for now I could only use a limited number of facets created from the attributes when aggregating by these facets. Is log export to monitor supported?**

**Describe the solution you'd like**
add a variable available from event message containing the whole log (that triggers the event) fields

**Comment by apigirl** [comment]
Hi @aitolkyn99 ,

Thanks for this suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
