### ISSUE TITLE
Network check docs missing info about collect_connection_state: true

### ISSUE THREAD

**Issue by shase** [DataDog/documentation#1234]
More specifically, this [page](http://docs.datadoghq.com/integrations/network/) is missing info about [this](https://github.com/DataDog/integrations-core/commit/6ccc9acaabe899b16bc2be714390456f371f9f7e) change.

thanks

**Comment by mide** [comment]
We're also encountering a need of information here. I'd be nice to have some documentations around `collect_connection_state: true` so we could debug.

**Comment by l0k0ms** [comment]
Hello @mide 

Sorry for the delay, thanks for the feedback! 
We added a description of the parameter in order to give more insights on its functionalities [here](https://docs.datadoghq.com/integrations/network/#configuration)

If you need deeper insights on how this collection is performed, then you should refer to 
https://github.com/DataDog/integrations-core/blob/master/network/check.py#L258
and
https://github.com/DataDog/integrations-core/blob/master/network/check.py#L634
Those are the two ways the DD-agent uses to collect your connections states.

If you need help to debug something, then I would strongly advise to reach out directly to our support team. They will be thrilled to help you to understand what may be happening with your infrastructure. 

Best regards,
Pierre
