### ISSUE TITLE
Tracing api documentation clarifications

### ISSUE THREAD

**Issue by chonton** [DataDog/documentation#1271]
trace_id, span_id: What is the size limitation (in bits) of integer?  Can the integer be negative?
name, service, resource: What is the length limitation? Can it be zero length?  Is there any range restriction on the individual characters?
meta: is there a conventional value/format for error information?
type: same questions as name, plus: are there any conventional values that are displayed differently?

In a root span (one without a parent_id), does trace_Id and span_id have the same value?

**Comment by kmshultz** [comment]
@chonton Thanks for your questions.

1. trace_id and span_id are 64-bit unsigned integers.
2. You can find the answers to some of your other questions in the Datadog app: https://app.datadoghq.com/apm/docs/tutorials/faq

I realize it's confusing that some documentation is in the app rather than the Docs website. We'll be working to get the Docs site filled out in the coming days/weeks.

**Comment by chonton** [comment]
Not all questions are answered:

1. are there any limitations to the values in the meta dictionary?
2. is there a conventional value/format for error information?
3. are there limitations to value of type?
4. are there any conventional values for type that will cause a different display in UI?
