### ISSUE TITLE
Kubernetes limitations paragraph seems unclear

### ISSUE THREAD

**Issue by pbitty** [DataDog/documentation#1388]
Hello,

From what I can tell, the Kubernetes agent check [by default](https://github.com/DataDog/integrations-core/blob/5.14.1/kubernetes/conf.yaml.example#L4-L28) connects to the `cAdvisor` instance each `kubelet` via `localhost:4194`.

However, in the documentation there is this note about [Limitations](https://github.com/DataDog/documentation/blob/d25a1b3e81edb3cf557383d9dcc7bb03d0548f7b/content/integrations/kubernetes.md#limitations):

> Please be aware that Kubernetes relies on Heapster to report metrics, rather than the cgroup file directly. The collection interval for Heapster is unknown which can lead to innacurate time-related data, such as CPU usage. If you require more precise metrics, we recommend using the Datadog-Docker Integration.
>
> Additionally please note that Heapster must be running in standalone mode.

If the check is talking to `cAdvisor` locally, I can't figure out where Heapster comes into play.  In my understand of the setup, it doesn't need Heapster at all to work.

Is someone able to clarify this or confirm?

If Heapster _is_ used, what is the reasoning behind the "must be running in standalone mode" requirement?

Thank you!

**Comment by l0k0ms** [comment]
Hello, 

It seems that this part is outdated, we do not rely on heapster anymore.
We now rely on the kubelet’s cadvisor, the kubelet and the apiserver (master)

We are going to update our readme in order to reflect this change, please excuse us for the misunderstanding.

Note: The docker integration is more precise for container metrics so we would still recommend using the Datadog-docker integration to gather them: https://app.datadoghq.com/account/settings#integrations/docker

Best, 
Pierre
