### ISSUE TITLE
alias key not documented.

### ISSUE THREAD

**Issue by mee** [DataDog/documentation#1423]
The following works, but the `alias` key does not appear in the documentation.

```
{
  "requests": [
    {
      "q": "avg:system.load.1{*}",
      "type": "line",
      "conditional_formats": [],
      "aggregator": "avg",
      "alias": "Load"
    }
  ],
  "viz": "timeseries"
}
```

Specific question I was looking for an answer to:

Can you provide a unique alias for each metric in something like the following?
```
"q": "avg:system.load.1{*},avg:system.load15{*}"
```

Specifying `"alias": ["foo","bar"]` appears to be equivalent to `"alias": "foo,bar"`

**Comment by l0k0ms** [comment]
Hello Mee, 

Thanks for the feedback, 
Could you please send us the link to the related documentation page?

Are you talking about our Screenboard documentation? https://docs.datadoghq.com/api/screenboards/ 

Regarding the behavior you noticed, I would suggest you contact directly our support team in order to open a bug fix / feature request. 

Best,

**Comment by mee** [comment]
Hi l0k0ms,

I would expect this to be documented here https://docs.datadoghq.com/graphingjson/ .

Thanks

**Comment by l0k0ms** [comment]
Hi Mee,

Thank you very much for this precision. We are going to work on this.

Regards,

**Comment by l0k0ms** [comment]
Hello Mee, 

After following with our Product management team, we indeed had a section in our doc under http://docs.datadoghq.com/graphingjson/#alias to describe this parameter.

But it was done over a feature that had been partially implemented i.e it does not actually work as previously described in the doc. That's why we removed the related doc.

Your alias will show up in the legend next to the metric some time, but not in any valuable way really.

We are currently working on a different way to address this use case, we will communicate [here](https://app.datadoghq.com/release_notes ) once the new feature is in production, and we will update the doc accordingly.

One more time, thank you very much for your feedback, 
Feel free to reach out to our support team if you have any question regarding your Datadog-application.
Best regards,
Pierre

**Comment by eliaslevy** [comment]
Curious about the status of different way to address this use case, as nothing on the release notes page seems to relate to it.  FWIW I am using `alias` and seems to work just fine.

**Comment by tomassommar** [comment]
I just checked http://docs.datadoghq.com/graphingjson/#alias and alias does not have a section there.

**Comment by l0k0ms** [comment]
Hello, 

The *alias* feature is not available on all widget. Hence you need to check at a widget specific API documentation in order to see if how the alias is supported:

https://docs.datadoghq.com/graphing/widgets/timeseries/#api

Best regards,
Pierre
