### ISSUE TITLE
Couldn't figure out how to configure Burn Rate alert based off documentation 

### ISSUE THREAD

**Issue by DavidS-cloud** [DataDog/documentation#15248]
## Documentation Page

content/en/monitors/service_level_objectives/burn_rate.md

## Issue Description

The page explains how to calculate burn rate, while the UI seems to expect error rates.

It would be much nicer if I could directly input the "remaining time until error budget exhaustion" in the UI, instead of this.

**Comment by apigirl** [comment]
Hi @DavidS-cloud,

Thanks for this suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
