### ISSUE TITLE
Trace API example uses GNU-specific commands

### ISSUE THREAD

**Issue by andor44** [DataDog/documentation#1705]
[This](https://github.com/DataDog/documentation/blob/a0aad5e0bc86ac0907fb2bc75657e63bbadebd88/code_snippets/trace-api-traces.sh) example uses the GNU-specific `%N` specifier for `date`, which will not work on macOS/BSD/other non-GNU coreutils. It'd be better if it used something that works on other platforms.

**Comment by irabinovitch** [comment]
@andor44 Thanks for your feedback. We'd be happy to adjust this to use non-GNU specific extensions. Unfortunately, bsd coreutils does not support resolution smaller than seconds. Any thoughts on alternative approaches?

**Comment by andor44** [comment]
If nanosecond precision is a hard requirement then portability gets tricky quickly. If the presence of a Python interpreter is a reasonable assumption this gets the job done:
```
$ python -c 'print(int(__import__("time").time() * 1000000))'
1509378951329485
```

**Comment by irabinovitch** [comment]
@andor44 nanoseconds are likely not required but milliseconds are for a useful trace.  Since the example here specifically is around bash/shell, I'm hesitant to have it depend on other languages. We should however add examples from more languages to the [trace api docs](https://docs.datadoghq.com/tracing/api/) as we have in our [core APIs](https://docs.datadoghq.com/api/)

Sound reasonable?

**Comment by l0k0ms** [comment]
Hello all, 

Documentation has been updated with corresponding code snippets.

Best regards,
Pierre
