### ISSUE TITLE
Is Trace API example accurate?

### ISSUE THREAD

**Issue by bmarini** [DataDog/documentation#1851]
## Documentation Page
https://docs.datadoghq.com/tracing/api/
https://github.com/DataDog/documentation/blob/master/code_snippets/trace-api-traces.sh#L18-L27

## Issue Description 
In the example traces are posted as `[[<trace hash>,...]]` is that accurate? Why the nested array?

**Comment by irabinovitch** [comment]
To save the next person looking a few minutes of searching.

The example file moved as part of our redesign to:
https://github.com/DataDog/documentation/blob/master/content/api/tracing/code_snippets/send_trace.sh#L18-L27

**Comment by l0k0ms** [comment]
Hello @bmarini,

The example is indeed accurate. I edited the API tracing description in order to explain why:
Traces can be sent as an array of traces:
 ```
 [ trace1, trace2, trace3 ]
 ``` 
 and each trace is an array of spans:
 ```
 trace1 = [ span, span2, span3 ]
 ```
 and each span is a dictionary with a `trace_id`, `spand_id`, `resource`.. hence the nested array.

With your issue, I spotted a minor error in python/ruby code snippets so thank you very much 🙇 

Feel free to reach out to us if you have any further questions or remarks.
Best regards,
Pierre
