### ISSUE TITLE
"series" is required, not optional

### ISSUE THREAD

**Issue by pepasflo** [DataDog/documentation#1998]
On this page in the docs: https://docs.datadoghq.com/api/?lang=bash#post-time-series-points

it says that the outer "series" key is optional.  As I've discovered the hard way, that's not true.  The API will still return a 202, but it silently throws your data away.

Here's a request which succeeds but gets thrown away:

<img width="1085" alt="screen shot 2018-01-29 at 10 26 08 am" src="https://user-images.githubusercontent.com/25310741/35524123-2e2b9082-04e6-11e8-89f3-c74b0eceee29.png">

Here's a request which succeeds and makes it through:

<img width="1094" alt="screen shot 2018-01-29 at 10 52 03 am" src="https://user-images.githubusercontent.com/25310741/35524143-455e8fca-04e6-11e8-848d-09aeb775de74.png">

Can you update the docs to say that "series" is required, rather than optional?

Thanks!

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback!!

When using curl, the `series` parameter is indeed required. It is, however, optional when using python, which may be where this confusion came from.

I updated the text to make it required all the time in order to avoid any confusion.

If you spot another glitch on our doc, feel free to open another issue!
Best regards,
Pierre

**Comment by pepasflo** [comment]
Thanks so much for jumping on this quickly!
