### ISSUE TITLE
New maintenance metrics for Consul integration

### ISSUE THREAD

**Issue by diogokiss** [DataDog/documentation#2187]
## Documentation Page

https://docs.datadoghq.com/integrations/consul

## Issue Description 

If https://github.com/DataDog/integrations-core/pull/1267 gets approved and merged, it will add two new metrics called `consul.catalog.services_maintenance` and `consul.catalog.nodes_maintenance` to Consul integration. It might be interesting to add it to the official documentation.

**Comment by l0k0ms** [comment]
Hello @diogokiss,

Many thanks for the update 🙇 
In order to display those new metrics on the documentation you just need to edit the metadata.csv file for the integration on integrations-core: https://github.com/DataDog/integrations-core/blob/master/consul/metadata.csv in your PR.

On each build we pull this file to generate the metrics table here: https://docs.datadoghq.com/integrations/consul/#metrics (even if it seems that it's broken right now.. :/)

I'm going to pass a fix to display the metric table on consul doc, could you add the new metric to the metadata.csv file?

Best regards,
Pierre

**Comment by diogokiss** [comment]
@l0k0ms, thanks for the instructions. I've updated the `metadata.csv` file in my PR (https://github.com/diogokiss/integrations-core/blob/ff6171d1865ac93a31084d94dae728e754b58606/consul/metadata.csv).

**Comment by l0k0ms** [comment]
Hello, 

The fix is merged for the metrics table, it will soon be displayed on the doc.
I'm going to close this issue for now, but if you spot other bugs or just have feedbacks regarding our documentation feel free to open a new one :)

Best regards,
Pierre
