### ISSUE TITLE
Add oracle.tablespace.offline metric documentation

### ISSUE THREAD

**Issue by dvanderveer** [DataDog/documentation#2348]
## Documentation Page
[https://docs.datadoghq.com/integrations/oracle/](https://docs.datadoghq.com/integrations/oracle/)

## Issue Description 
`integrations-core` pull request [1403](https://github.com/DataDog/integrations-core/pull/1403) adds metric `oracle.tablespace.offline`.  If the pull request is accepted the documentation for the new metric would need to be added, e.g.:

oracle.tablespace.offline (gauge)
tablespace offline, shown as boolean

**Comment by l0k0ms** [comment]
Hello @dvanderveer,

Many thanks for the update 🙇 
In order to display this new metric on the documentation you just need to edit the metadata.csv file for the oracle integration on integrations-core: https://github.com/DataDog/integrations-core/blob/master/oracle/metadata.csv in your PR.

On each build we pull this file to generate the metrics table here: https://docs.datadoghq.com/integrations/oracle/#metrics

Could you edit your PR directly? 
Best regards,
Pierre

**Comment by dvanderveer** [comment]
The PR already contains the necessary addition in `metadata.csv`, so it looks like no extra docs work is required.  Closing this issue.
