### ISSUE TITLE
Add docker.cpu.shares metric documentation

### ISSUE THREAD

**Issue by winebarrel** [DataDog/documentation#2351]
## Documentation Page

https://docs.datadoghq.com/integrations/docker_daemon/

## Issue Description 

https://github.com/DataDog/integrations-core/pull/1358 adds `docker.cpu.shares`.
it is necessary to update the document if PR is merged.

**Comment by l0k0ms** [comment]
Hello @winebarrel 

Many thanks for the update 🙇 
In order to display this new metric on the documentation you just need to edit the metadata.csv file for the docker_daemon integration on integrations-core: https://github.com/DataDog/integrations-core/blob/master/docker_daemon/metadata.csv in your PR.

On each build we pull this file to generate the metrics table here: https://docs.datadoghq.com/integrations/docker_daemon/#metrics

Could you edit your PR directly? 
Best regards,
Pierre

**Comment by l0k0ms** [comment]
It seems that you already done it :)

When your PR will be merged to integrations-core, your new metric and its description will be displayed automatically on  https://docs.datadoghq.com/integrations/docker_daemon/

Well done!
Best regards,
Pierre

**Comment by winebarrel** [comment]
Thank you for answering 😃
