### ISSUE TITLE
Clarification Needed on ORGADMIN Permissions for Collecting Organization Metrics in Snowflake Integration

### ISSUE THREAD

**Issue by edmamerto** [DataDog/documentation#23838]
## Documentation Page
https://docs.datadoghq.com/integrations/snowflake_web/

## Description of the Issue

The [documentation](https://docs.datadoghq.com/integrations/snowflake_web/) mentions that to gather organization metrics, the user needs ORGADMIN permissions.

![image](https://github.com/DataDog/documentation/assets/11814798/4bae6d04-acaf-4aee-8a3a-24d99f304710)

Contrastingly, the Snowflake documentation at 📄 [Account Usage/Enabling other roles to use schemas in the SNOWFLAKE database]( https://docs.snowflake.com/en/sql-reference/account-usage#label-enabling-usage-for-other-roles) suggests that having ORGADMIN enabled on the account (not necessarily assigned to the user) and access to the SNOWFLAKE database suffices for viewing organizational metrics.

![image](https://github.com/DataDog/documentation/assets/11814798/510af0c6-3e68-4cfb-93d9-2ca4a75743aa)

**Comment by buraizu** [comment]
@edmamerto thank you for reaching out. I'm validating this internally and will follow up as soon as I have any updates.

**Comment by edmamerto** [comment]
@buraizu Forgot to mention I did not have to make the user ORGADMIN and it worked

**Comment by buraizu** [comment]
@edmamerto Thanks again for your patience while I've been following up internally about this. To clarify, we mean that the account that creates the user must have the ORGADMIN role, and since we provide the instruction to run `grant imported privileges on database SNOWFLAKE`, this passes those permissions to the user.

If the account has access but doesn’t run the command or pass the permissions to the user that is created, the user will not have access to the ORGANIZATION_USAGE schema.

With that said, the team is doing some experimentation with database roles on Snowflake to see if there’s an easier alternative to the steps we currently provide. I’ll follow up here again as soon as we have any updates.

**Comment by buraizu** [comment]
Hi @edmamerto, thanks again for your patience while I followed up internally about this. Our engineers have let me know that they’ve made an update in this regard:
https://docs.datadoghq.com/integrations/snowflake_web/#cloud-cost-management

Please let me know if you have any additional questions.

**Comment by buraizu** [comment]
Hi @edmamerto, as we haven't heard back from you, I'll close this issue for now. Please feel free to reopen the issue if you have any further questions or feedback.
