### ISSUE TITLE
Add filebeat.registry.offset to csv

### ISSUE THREAD

**Issue by danielkasen** [DataDog/documentation#4437]
Pull request to add filebeat.registry.offset to the csv as the total uncompressed value of a log file. Different then 'libbeat.output.write.bytes." Tied to https://github.com/DataDog/integrations-extras/pull/420

**Comment by l0k0ms** [comment]
Hello, @danielkasen 

Many thanks for the ping 🙇,  In order to add the metrics in the public documentation you would need to add the appropriate metrics here: https://github.com/DataDog/integrations-extras/blob/master/filebeat/metadata.csv I see that you have an open PR to update the Datadog-Filebeat integration let's follow this discussion there: https://github.com/DataDog/integrations-extras/pull/423

Best,
Pierre
