### ISSUE TITLE
Failing to build wheel

### ISSUE THREAD

**Issue by obthearchitect** [DataDog/documentation#5206]
Greetings and apologies if this is not the correct forum for this, but I'm unable to get this running on python3.5.3. Whenever it triest to build wheel for `PyGitHub`, `pycparser`, `cffi`, `htmlmin`, `PyYAML`, `simplejson`, `datadog`, I get the error below. 

I've double-checked to make sure that wheel is updated, and I've even tried uninstalling it with no luck. Has anyone bumped into this issue?

`pip install --upgrade pip` =>  ('Requirement already up-to-date')
`pip install setuptools --upgrade` =>  ('Requirement already up-to-date')

```Failed building wheel for datadog
  Running setup.py clean for datadog
  Running setup.py bdist_wheel for simplejson ... error
  Complete output from command /home/obthearchitect/documentation/hugpython/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8qggtql5/simplejson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp74lbfg35pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help```

**Comment by apigirl** [comment]
Hi @obthearchitect - Hi @sebdeckers - sorry you are running into this issue! In order to best support you, we ask that you [file a ticket with our support team](https://docs.datadoghq.com/help/).

Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you have any other issues.

~ Datadog Documentation Team
