### ISSUE TITLE
Downloadable file for JavaScript application

### ISSUE THREAD

**Issue by sohamneogi24** [DataDog/documentation#5550]
I would want to download the javascript file for datadog instead of linking to the CDN so that I'm able to monitor the changes in the version before integrating with my application

**Comment by bcaudan** [comment]
Hi @sohamneogi24!
I am working in the team developing the Datadog javascript logging library. 
We are planning to make this library available as a npm package in the coming weeks.
It would allow you to choose which version you want to integrate with your application.

**Comment by sohamneogi24** [comment]
Hi @bcaudan !
Thanks for the quick response.
That will be great, could you notify me when that is in place?

**Comment by apigirl** [comment]
hi @sohamneogi24 - If you [file a ticket with our support team](https://docs.datadoghq.com/help/) describing the request and linking here, they have a system in place to let people know when functionality they've requested has been released.

Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you have any other issues.
