### ISSUE TITLE
Add ability to send dedup_key with DD monitors for PagerDuty

### ISSUE THREAD

**Issue by jbruns2019** [DataDog/documentation#5736]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
On DD monitors using email notify techniques, we can send an alert to PagerDuty to open an alert and if so configured, an incident in ServiceNow, which we do.  Allow me to send the dedup_key json attribute so that PagerDuty will not open another alert/INC if there is already one open for same key.

See https://support.pagerduty.com/docs/event-management

**Describe alternatives you've considered**
None, DD does not offer this

**Additional context**

**Comment by l0k0ms** [comment]
Hello @jbruns2019 

Thanks so much for this feedback! Since this is a product enhancement request, we ask that you [file a ticket with our support team](https://docs.datadoghq.com/help/) - they have a system in place to follow up on and track enhancement requests, and they will also let you know if we eventually do end up deciding to support this. 

Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you notice any issues or have any other suggestions.

Best,
Pierre
