### ISSUE TITLE
Missing data settings

### ISSUE THREAD

**Issue by jbruns2019** [DataDog/documentation#5766]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

In the monitor setup in DD, there is a missing data filter to set off an alert if the data is missing for x minutes.  Minutes is the only option to filter on.  We need more choices, like days, weeks, months not just minutes

**Describe alternatives you've considered**

**Additional context**

**Comment by l0k0ms** [comment]
Hello @jbruns2019,

Thanks so much for this feedback! Since this is a product enhancement request, we ask that you [file a ticket with our support team](https://docs.datadoghq.com/help/) - they have a system in place to follow up on and track enhancement requests, and they will also let you know if we eventually do end up deciding to support this. 

Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you notice any issues or have any other suggestions.

Best,
Pierre
