### ISSUE TITLE
Set alert conditions

### ISSUE THREAD

**Issue by jbruns2019** [DataDog/documentation#5767]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

For alert conditions, where we see "Trigger when the metric is", allow the customer to set the "during the last" values by 1) allow me to pick the number and 2) add days and weeks as options.  You will need to remove the current drop down or change it to just picking a number then add a new drop down to the right of that to pick interval amounts, like seconds, minutes, hours, days, weeks.

**Describe alternatives you've considered**

**Additional context**

**Comment by l0k0ms** [comment]
Hello @jbruns2019 ,

Thanks so much for this feedback! Since this is a product enhancement request, we ask that you [file a ticket with our support team](https://docs.datadoghq.com/help/) - they have a system in place to follow up on and track enhancement requests, and they will also let you know if we eventually do end up deciding to support this. 

Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you notice any issues or have any other suggestions.

Best,
Pierre
