### ISSUE TITLE
Short Links

### ISSUE THREAD

**Issue by mkw** [DataDog/documentation#6351]
**Is your feature request related to a problem? Please describe.**
DataDog URLs are long and complicated, and there is no guarantee (that I know of) that DataDog will keep the format consistent over time.

**Describe the solution you'd like**
A button to copy a short url like https://lnk.datadoghq/abc123 somewhere on every page with the following properties:

- Guaranteed to work for a declared period of time (e.g. 1-2 years)
- Above implies that any changes to parameters or other URL details will be migrated server-side before the required redirect.
- Includes all state related to the graph.

Over the top ideas:

- Editable by owning user (e.g. target can be changed from some dashboard)
- Vanity URLs -- e.g. mycompany.datadoghq.com/my-target-vanity-name

**Describe alternatives you've considered**
I use our internal link shortening system, with varying success.

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback 🙇 but i think you are speaking about the Datadog app URLs. This repository is only for the Datadog documentation. 

In order to open a Feature Request for the Datadog application you should open a Ticket to `support@datadoghq.com`. They will ensure a proper transmission and follow up with the appropriate engineering team.

I'm going to go ahead and close this issue for now, but feel free to re-open it if you have any questions.

Best regards,
Pierre

**Comment by mkw** [comment]
Thanks -- I noticed that right after I submitted. Sorry about the noise!
