### ISSUE TITLE
Network Monitoring discrepancy with Helm chart

### ISSUE THREAD

**Issue by jaygorrell** [DataDog/documentation#6391]
## Documentation Page
https://docs.datadoghq.com/network_performance_monitoring/installation/?tab=kubernetes

## Issue Description
Enabling the network map through Helm calls for the following:
```
systemProbe:
  (...)
  enabled: true

(...)

daemonset:
  useDedicatedContainers: true
```
This results in the following changes:
`process-agent`:
- Env var: `DD_PROCESS_AGENT_ENABLED: "true"`
- Env var: `DD_SYSTEM_PROBE_ENABLED: "true"`
- volumeMount: `sysprobe-socket-dir: /opt/datadog-agent/run`

`system-probe`:
- [new container with no env vars]

However, the above documentation page for a manual Kubernetes setup calls for adding the following env vars to the agent container:
```
- {name: DD_PROCESS_AGENT_ENABLED, value: "true"}
- {name: DD_SYSTEM_PROBE_ENABLED, value: "true"}
- {name: DD_SYSTEM_PROBE_EXTERNAL, value: "true"}
- {name: DD_SYSPROBE_SOCKET, value: "/var/run/s6/sysprobe.sock"}
```
and these to the system-probe container:
```
- {name: DD_SYSTEM_PROBE_ENABLED, value: "true"}
- {name: DD_SYSPROBE_SOCKET, value: "/var/run/s6/sysprobe.sock"}
```

There are a couple things confusing here:
- The helm chart does not include `DD_SYSTEM_PROBE_EXTERNAL` while the documentation does, yet neither one makes mention of what it does.
- The helm chart only adds `DD_SYSTEM_PROBE_ENABLED` to the process-agent container but the documentation says it should be on the agent container as well.

**Comment by shang-wang** [comment]
Hi @jaygorrell, it's complicated by design, so I'll try to put something see if it makes sense to you.

Some facts:
1. The network monitoring functionality needs both process-agent and system-probe agent to run.
2. The datadog-agent image ships with all agent services, this includes process-agent, datdadog-agent and system-probe agent.
3. The system-probe agent would always need to run in dedicated container for security reason.

The reason they are different is because using helm chart requires `useDedicatedContainers: true`, which essentially will run datadog-agent, process-agent and system-probe agent in dedicated containers.

However, for the setup in the official documentation, process-agent and datadog-agent are running in the same container, but since system-probe agent needs to be on dedicated container, we need `DD_SYSTEM_PROBE_ENABLED: true` on main agent container to make sure it doesn't keep trying to start system-probe agent service because it shouldn't be running on it. At the same time, it needs `DD_SYSTEM_PROBE_ENABLED: true` so process-agent is aware of the existence of system-probe agent so it'll pull network information from it.

This problem doesn't exist in helm setup because the dedicated process-agent container explicitly runs process-agent only: https://github.com/helm/charts/blob/8f30dd815fe1126a4b9e43b71a10d750640d8f31/stable/datadog/templates/container-process-agent.yaml#L5. 

As you can see this is hard to reason so we didn't put up any documentation to confuse users. But I'll make sure there's comment on the official doc regarding the usage of `DD_SYSTEM_PROBE_EXTERNAL`. Thanks.

**Comment by jaygorrell** [comment]
Thank you for that great explanation. I think just getting `DD_SYSTEM_PROBE_EXTERNAL` documented sounds good to me then.

**Comment by shlomoartzi** [comment]
Hi Jay! I just wanted to let you know we have updated our docs https://docs.datadoghq.com/network_performance_monitoring/installation/?tab=kubernetes. Thanks so much for your helpful feedback.

**Comment by shang-wang** [comment]
Since the documentation update is in place I'm going to resolve this issue for now. Feel free to follow up if there's more question.
