### ISSUE TITLE
Typo in the Attributes - Performance section

### ISSUE THREAD

**Issue by rmustard** [DataDog/documentation#6661]
## Documentation Page
https://docs.datadoghq.com/logs/processing/attributes_naming_convention/#performance

## Issue Description
Original sentence :
"Datadog advises you to rely or at least remap on this attribute since Datadog displays and uses it as a default measure for trace search."

I'm not sure what rely means.

**Comment by l0k0ms** [comment]
hello,

Indeed there is a link missing to the remapper processor to explain how to remap.

The idea is that if you have a "duration" expressed in your logs, like your web-servers response time, or your DB response time, but this duration is in an attribute like `db.response_time` or `http.response_time` then Datadog advise you to remap the values of this original attribute to the Standard attributes `duration` in order to benefit from OOTB functionalities within the Datadog application. I have open a PR to address this confusion.

Does this answer your question ?

Best,
Pierre

**Comment by rmustard** [comment]
Yes that makes sense.  Thanks!

**Comment by l0k0ms** [comment]
Closing this issue then :) 

If you spot other glitches in our doc feel free to open a new one.
