### ISSUE TITLE
Clarify when as_rate is _not_ per second

### ISSUE THREAD

**Issue by bplotnick** [DataDog/documentation#6662]
## Documentation Page
https://github.com/DataDog/documentation/blob/master/content/en/developers/metrics/type_modifiers.md

## Issue Description
On the Metric Type Modifiers page it says `RATE: Normalized value variation over time (usually per seconds).`

This has two issues:
1. It says "usually", so presumably there are cases where it is not per second, however there is no obvious mention of when this is the case. It seems like a detail that would have a big impact.
2. nit: s/seconds/second/

**Comment by l0k0ms** [comment]
Hello,

Indeed you're right the usually can be misleading. It's always stored "per second", it's just that if you look at a RATE metric over a whole year, it will be displayed as RATE "per day" because of the minimum roll up interval applied.

I've open a PR to fix it, many thanks for this feedback 🙇 
I'm going to close this PR for now, but feel free to re-open it if you have more questions.

Best,
Pierre
