### ISSUE TITLE
Issues changing an integration's name

### ISSUE THREAD

**Issue by sachindshinde** [DataDog/documentation#6868]
Due to some rebranding on our end, we changed our Datadog integration's name from "Apollo Engine" to "Apollo", through changes in the [integration-extras](https://github.com/DataDog/integrations-extras) repo.

However, we've had a few issues since then:
- The docs page with the new integration name properly appears at https://docs.datadoghq.com/integrations/apollo/ . However, the docs page with the old integration name is still being served at https://docs.datadoghq.com/integrations/apollo_engine/ , and it still appears in Google searches.
- On https://app.datadoghq.com/account/settings#integrations , the tile for only the old integration name appears, along with the old logo.
- On https://docs.datadoghq.com/integrations/ , I don't see any tile at all for "Apollo" (nor for the old "Apollo Engine")

**Comment by l0k0ms** [comment]
Hello,

Many thanks for this feedback!  I've open 2 PR to fix this:

* https://github.com/DataDog/integrations-extras/pull/554 adds an alias to redirect traffic from Apollo engine doc page to the new Apollo page
* https://github.com/DataDog/documentation/pull/6870 updates the logo name so that it's displayed in the main integrations page. 

I'm going to go ahead and close this issue for now, but if you have other feedback feel free to re-open it, or open a new issue shall you spot another glitch with our doc :) 

Best, 
Pierre
