### ISSUE TITLE
Custom Agent Check 'guage' Documentation and Example Usage is Incorrect

### ISSUE THREAD

**Issue by coofercat** [DataDog/documentation#6895]
## Documentation Page

https://docs.datadoghq.com/developers/metrics/agent_metrics_submission/?tab=gauge
https://docs.datadoghq.com/developers/write_agent_check/?tab=agentv6v7

## Issue Description

I _think_ the parameter documentation for the `gauge` method and example code thereof are incorrect. I couldn't get tags to work as documented:

`self.gauge('metric_name', 1234, tags=['tag:value'])`

Doing this, and then performing a dev test (`sudo -u dd-agent -- datadog-agent check mycheck`) shows none of the metrics tagged. To resolve, I used:

`self.gauge('metric_name', 1234, ['tag:value'])`

My agent version is:

`Agent 7.16.0 - Commit: 3e13b77 - Serialization version: 4.15.0 - Go version: go1.12.9`

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for the feedback!

🤔 That's weird because this is the correct implementation that can be found in many Datadog official checks:

* [Yarn check](https://github.com/DataDog/integrations-core/blob/14ef6bd4ddcca25a901d7d78bf88a1f6a12e373a/yarn/datadog_checks/yarn/yarn.py#L354) 
* [Vertica check](https://github.com/DataDog/integrations-core/blob/5693dc717d4e41533aa693e2a87ad90f08a5985a/vertica/datadog_checks/vertica/vertica.py#L137)
* [Mesos check](https://github.com/DataDog/integrations-core/blob/c17e61331357691c6bac286d71a443d4b20d7492/mesos_master/datadog_checks/mesos_master/mesos_master.py#L266)

There might be something else at stake here.. Could you reach out to support@datadoghq.com to see if there is something fishy below all of this ?

I'm going to close this issue for now. If there is indeed an issue with the function support will reach out to us with the fix and we will update the doc :) 
But if you have more details or questions, feel free to re-open it and add your comments ! 

Best regards,
Pierre
