### ISSUE TITLE
Artifact Id is not present in Central Maven Repository

### ISSUE THREAD

**Issue by ankumar-apptio** [DataDog/documentation#7270]
I am not able to download the jars using the artifact id provided:
<dependency>
  <groupId>com.datadoghq</groupId>
  <artifactId>datadog-api-client</artifactId>
  <version>1.0.0</version>
  <scope>compile</scope>
</dependency>

Checked this artifact id is not present in central repository also.

Can you please help me out of this or there is change in artifact id ?

**Comment by sarina-dd** [comment]
Hi @ankumar-apptio ,
Thanks so much for this feedback! It looks like this issue is tracked and is in progress here: [datadog-api-client-java repo issue](https://github.com/DataDog/datadog-api-client-java/issues/254). Going to close this issue on our end as this issue will be tracked within that repo.

Sarina
