### ISSUE TITLE
As a user I want to see the last logon time to detect a possible malicious logon in my account.

### ISSUE THREAD

**Issue by balduinmetz** [DataDog/documentation#7973]
**Describe the solution you'd like**
Datadog notifies the user, upon successful logon (access) to the user interface, of the date and time of the last logon (access).

**Describe alternatives you've considered**
In case a specific notification upon each login is hampering user experience, different options could be possible:
* Logon time is visualized on the user interface (footer) without active notification
* Suspicious login from unknown devices are reported via mail
* Personal profile tab which shows last sessions, devices etc. that have been used to logon to datadog by the user.

**Comment by apigirl** [comment]
Hi @balduinmetz,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep track of feature requests and are often able to let you know when and if we do decide to move forward with an idea. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
