### ISSUE TITLE
Feature Request: Synthetic Test check what is in the downloaded folder / archive 

### ISSUE THREAD

**Issue by captainKeller** [DataDog/documentation#8642]
It would be great if you can check the Synthetic Browser Test in the assertion "test a downloaded file" what is contained in an archive.

**Comment by apigirl** [comment]
Hi @skang0601,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
