### ISSUE TITLE
display @batch_time as a date-time

### ISSUE THREAD

**Issue by keraterink-spire** [DataDog/documentation#8689]
When analyzing logs coming in from remote Android devices, it is occasionally useful to see if those logs have been delayed. My understanding is that @batch_time is the 'ingestion' timestamp at the DataDog servers. It would be great if we could display that as a date/time next to the log date/time for easy comparison in this situation.
![Screen Shot 2020-09-30 at 9 53 14 AM](https://user-images.githubusercontent.com/54415613/94702013-e747ea80-0302-11eb-9d11-1acbcd8702a8.png)

**Comment by apigirl** [comment]
Hi @skang0601,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
