### ISSUE TITLE
Display APM service related Dashboards in APM page

### ISSUE THREAD

**Issue by skang0601** [DataDog/documentation#8723]
**Is your feature request related to a problem? Please describe.**
It's a little frustrating to find all the related dashboards for APM service I'm looking at.

**Describe the solution you'd like**
The APM page already serves as the central location for developers to view things such as monitors, traces, metrics, profiling, and infrastructure metrics. It would be nice if related dashboards can also be linked alongside with the service I'm viewing on the APM page as a separate tab. Things like ALB, database, or other infrastructure dashboards should all be accessible and discoverable from this central location.

**Describe alternatives you've considered**
Filtering through the dashboard lists using tags. Often times they have the same service/env tags used by the APM.

**Additional context**

**Comment by apigirl** [comment]
Hi @skang0601,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
