### ISSUE TITLE
Oracle Public Cloud Integration Support 

### ISSUE THREAD

**Issue by ankanch** [DataDog/documentation#8937]
**Is your feature request related to a problem? Please describe.**
I want to monitor my servers on the oracle public cloud. Like metrics in AWS.

**Describe the solution you'd like**
Integration support for monitoring on Oracle Public Cloud, just like AWS.

**Describe alternatives you've considered**
Install Dtadog Agent on every  500 servers.

**Additional context**
No.

**Comment by apigirl** [comment]
Hi @ankanch,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. If there's not currently a workaround, they also can track product requests and let you know if we move to add the functionality. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
