### ISSUE TITLE
provide a hover-over hint or tooltip with the name of custom events in graphs

### ISSUE THREAD

**Issue by rfulwell** [DataDog/documentation#9320]
We are using custom events to display when deployments occur but it can be difficult to tell which deployment is shown.

Some UI with a popup, hover-over, or tooltip that provides the tag name would be helpful.

![image](https://user-images.githubusercontent.com/470472/102648528-83bca480-411c-11eb-8fca-5b268e92241c.png)

In the image above, it is cumbersome to figure out what the three pink deployment events represent.

**Comment by apigirl** [comment]
Hi @rfulwell,

Thanks for the suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
