### ISSUE TITLE
Feature Request: Incident management tool: analytic dashboard

### ISSUE THREAD

**Issue by ai-denlim** [DataDog/documentation#9734]
Our dev-team started using the Datadog `incident management tool` to respond to major incidents in a more organized/curated manner. The tool's overall experience has been great, except that it's hard to get an overview of overall incident operational history. As a new feature to the incident management tool, I want to request an analytic dashboard that offers insight into overall incident operational reviews, including measurement of `MTTR` and `MTTA`.

Alternative solution: expose or allow access to metadata of recorded incidents

**Comment by apigirl** [comment]
Hi @ai-denlim ,

Thanks for this suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
