### ISSUE TITLE
SIGNL4 Alerting Added

### ISSUE THREAD

**Issue by rons4** [DataDog/documentation#9794]
As mentioned in the checklist I would like you to notify about this pull request:  https://github.com/DataDog/integrations-extras/pull/807

**Comment by apigirl** [comment]
Hi @rons4 - thanks for letting us know! When your PR is merged into master of integrations-extras, within a couple of hours, our documentation pipeline automatically picks up `signl4/README.md` and builds it at https://docs.datadoghq.com/integrations/signal4/ (not currently live).

I am going to close this for now since it's already covered, but again, thanks for letting us know!

Kaylyn

**Comment by rons4** [comment]
Thanks a lot @apigirl.
Ron

**Comment by rons4** [comment]
Hi @apigirl, the integration is live now (https://docs.datadoghq.com/integrations/signl4/). Thanks a lot.

However, can we replace the logo on the listing page (https://docs.datadoghq.com/integrations/) with the attached one?

![SIGNL4_logo_rounded](https://user-images.githubusercontent.com/43244104/110140058-fa8c4400-7dd3-11eb-824d-b0b3e46969e8.png)

If you should not be the right contact for this request, maybe you can point me into the right direction.

Thanks

Ron
