### ISSUE TITLE
Feature Request: Allow the sharing of notebooks publicly (like dashboards)

### ISSUE THREAD

**Issue by bolteddown** [DataDog/documentation#9890]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.

**Describe the solution you'd like**
A menu option that generates a public URL and provides options for making a notebook public. We'd like to provide links to notebooks to consultants.

**Describe alternatives you've considered**
We have made dashboards for this purpose but prefer the adhoc nature of notebooks.

**Additional context**
None

**Comment by apigirl** [comment]
Hi @bolteddown,

Thanks for this suggestion! Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they keep a list of feature requests and who has requested them, so they'll be able to let you know if Datadog moves forward with adding this. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
